# Generated by Django 4.2.23 on 2025-08-09 09:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resumeLink', models.URLField()),
                ('coverLetter', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Reviewed', 'Reviewed'), ('Interview', 'Interview'), ('Rejected', 'Rejected'), ('Hired', 'Hired')], default='Applied', max_length=10)),
                ('appliedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
